{% set name = "glom" %}
{% set version = "19.10.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: c8a50cb9fcf0c84807836c6a73cf61285557834b9050d7bde7732b936aceb7dd

build:
  number: 0
  entry_points:
    - glom = glom.cli:console_main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - attrs
    - boltons
    - face
    - python

test:
  imports:
    - glom
    - glom.test
  commands:
    - glom --help

about:
  home: "https://github.com/mahmoud/glom"
  license: "BSD-3-Clause"
  license_family: "BSD"
  license_file: "LICENSE"
  summary: "A declarative object transformer and formatter, for conglomerating nested data."

extra:
  recipe-maintainers:
    - CJ-Wright
