{% set name = "glom" %}
{% set version = "24.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4325f96759a912044af7b6c6bd0dba44ad8c1eb6038aab057329661d2021bb27

build:
  number: 0
  entry_points:
    - glom = glom.cli:console_main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - attrs
    - boltons >=19.3.0
    - face >=20.1.1
    - python >={{ python_min }}

test:
  source_files:
    - glom/test
  imports:
    - glom
  commands:
    - pip check
    - glom --help
    - pytest -vvv --capture=tee-sys -k "not test_error" glom/test
  requires:
    - pip
    - pytest >=6.2.5
    - pyyaml ==5.4.1
    - python {{ python_min }}

about:
  home: https://github.com/mahmoud/glom
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A declarative object transformer and formatter, for conglomerating nested data.

extra:
  recipe-maintainers:
    - CJ-Wright
    - thewchan
